language: c

sudo: false
dist: xenial

env:
  - BUILD_CONFIG=artik053/onboard
  - BUILD_CONFIG=artik053s/onboard
  - BUILD_CONFIG=artik055s/onboard

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential git gcc-arm-none-eabi gdb-arm-none-eabi

install:
  - git clone https://github.com/SamsungARTIK/TizenRT.git

script:
  - cd os/tools; ./configure.sh ${BUILD_CONFIG}
  - cd ..; make